"""Serving-time embedding path: same model as `embedder.py`, without torch.

Why this exists at all: `app/ingestion/embedder.py` loads all-MiniLM-L6-v2
through sentence-transformers, which imports torch. Measured on the serving
path, `import torch` alone costs ~315MB RSS *before any weights load*, and
the whole process peaks around 350MB. Render's free container is capped at
512MB total (including the gunicorn master), so the API process was being
OOM-killed by the kernel the moment a /search request triggered that import
-- with no application-level traceback, since the kernel kills the container
outright.

This module runs the *same weights* (`onnx/model.onnx` from the same HF repo)
through onnxruntime instead, and reimplements the two post-processing steps
sentence-transformers stacks on top of the transformer, per that repo's
`modules.json`: mean pooling over tokens (`1_Pooling/config.json` sets
`pooling_mode_mean_tokens: true`) followed by L2 normalization.

Because the weights are identical, vectors produced here match the
sentence-transformers ones to within float noise -- verified by
`tests/unit/test_onnx_embedder.py`, which asserts cosine similarity > 0.9999
against the torch path. That matters: the ~883K chunk embeddings already in
Postgres were generated by the torch path during ingestion, and query vectors
have to land in the same space for cosine distance to mean anything.

Ingestion deliberately keeps using the torch path -- it runs on a laptop with
no memory ceiling, batches far more aggressively, and there's no reason to
revalidate a pipeline whose output is already in the database.
"""

from functools import lru_cache
from typing import TYPE_CHECKING

import numpy as np

if TYPE_CHECKING:  # pragma: no cover - import-time cost avoided at runtime
    import onnxruntime as ort
    from tokenizers import Tokenizer

HF_REPO = "sentence-transformers/all-MiniLM-L6-v2"
ONNX_FILENAME = "onnx/model.onnx"
TOKENIZER_FILENAME = "tokenizer.json"

# From the model repo's sentence_bert_config.json. Chunks were embedded with
# this same ceiling during ingestion, so queries must use it too.
MAX_SEQ_LENGTH = 256
EMBEDDING_DIM = 384


@lru_cache(maxsize=1)
def get_tokenizer() -> "Tokenizer":
    from huggingface_hub import hf_hub_download
    from tokenizers import Tokenizer

    tokenizer = Tokenizer.from_file(hf_hub_download(HF_REPO, TOKENIZER_FILENAME))
    tokenizer.enable_truncation(max_length=MAX_SEQ_LENGTH)
    tokenizer.enable_padding()
    return tokenizer


@lru_cache(maxsize=1)
def get_session() -> "ort.InferenceSession":
    import onnxruntime as ort
    from huggingface_hub import hf_hub_download

    options = ort.SessionOptions()
    # Render's free instance is 0.1 CPU. Letting onnxruntime spin up a thread
    # per core measurably hurts there rather than helping: the threads just
    # contend for a fraction of one core.
    options.intra_op_num_threads = 1
    options.inter_op_num_threads = 1
    return ort.InferenceSession(
        hf_hub_download(HF_REPO, ONNX_FILENAME),
        sess_options=options,
        providers=["CPUExecutionProvider"],
    )


def _mean_pool(last_hidden_state: np.ndarray, attention_mask: np.ndarray) -> np.ndarray:
    """Average token vectors, ignoring padding.

    Padding tokens carry real values in `last_hidden_state`, so a plain
    `.mean(axis=1)` would blend them in and make a vector depend on how much
    padding its batch happened to need. Masking first is what makes the result
    batch-independent, and is what sentence-transformers' Pooling module does.
    """
    mask = attention_mask[..., None].astype(np.float32)
    summed = (last_hidden_state * mask).sum(axis=1)
    counts = np.clip(mask.sum(axis=1), a_min=1e-9, a_max=None)
    return summed / counts


def _l2_normalize(vectors: np.ndarray) -> np.ndarray:
    norms = np.linalg.norm(vectors, axis=1, keepdims=True)
    return vectors / np.clip(norms, a_min=1e-12, a_max=None)


def embed_texts_onnx(texts: list[str], batch_size: int = 32) -> list[list[float]]:
    """Embed texts to unit-length 384-dim vectors, matching the torch path."""
    if not texts:
        return []

    tokenizer = get_tokenizer()
    session = get_session()

    out: list[list[float]] = []
    for start in range(0, len(texts), batch_size):
        encodings = tokenizer.encode_batch(texts[start : start + batch_size])
        inputs = {
            "input_ids": np.array([e.ids for e in encodings], dtype=np.int64),
            "attention_mask": np.array([e.attention_mask for e in encodings], dtype=np.int64),
            "token_type_ids": np.array([e.type_ids for e in encodings], dtype=np.int64),
        }
        [last_hidden_state] = session.run(["last_hidden_state"], inputs)
        pooled = _l2_normalize(_mean_pool(last_hidden_state, inputs["attention_mask"]))
        out.extend(pooled.astype(np.float32).tolist())
    return out
